version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - POSTGRES_DB=disasterAllocation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S#wet@46
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=disasterAllocation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S#wet@46
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
